# Generated by Django 3.1.12 on 2025-07-14 21:08

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast3Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kp_index', djongo.models.fields.JSONField(default=list)),
                ('solar_radiation', djongo.models.fields.JSONField(default=list)),
                ('radio_blackout', djongo.models.fields.JSONField(default=dict)),
                ('rationale_geomagnetic', models.TextField()),
                ('rationale_radiation', models.TextField()),
                ('rationale_blackout', models.TextField()),
            ],
        ),
    ]
