# Generated by Django 3.1.12 on 2025-09-18 17:06

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast3Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('radio_flux', models.FloatField(blank=True, null=True)),
                ('a_index', models.IntegerField(blank=True, null=True)),
                ('kp_index', djongo.models.fields.JSONField(blank=True, default=list)),
                ('solar_radiation', djongo.models.fields.JSONField(blank=True, default=list)),
                ('radio_blackout', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('rationale_geomagnetic', models.TextField(blank=True, default='')),
                ('rationale_radiation', models.TextField(blank=True, default='')),
                ('rationale_blackout', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'forecast_forecast3day',
            },
        ),
    ]
